{% set name = "freesasa" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/freesasa-{{ version }}.tar.gz
  sha256: 5630e65d619cf6a062028d7c6297afe8c5b18c677c75f1c32a0938399f4f6850

build:
  script_env:
    - USE_CYTHON=1
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - cython >=0.29.13
    - pip
  run:
    - python

test:
  imports:
    - freesasa
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://freesasa.github.io/
  summary: Calculate solvent accessible surface areas of proteins
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - pgbarletta
