{% set name = "freesasa" %}
{% set version = "2.2.0.post3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/freesasa-{{ version }}.tar.gz
  sha256: db7e5c8a1deae051198d5c7e1a54f2d001b22a945b524d81cb26cacb7d6bb54f

build:
  script_env:
    - USE_CYTHON=1
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython >=0.29.13
    - pip
  run:
    - python

test:
  imports:
    - freesasa
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://freesasa.github.io/
  summary: Calculate solvent accessible surface areas of proteins
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - pgbarletta
